#!/usr/bin/env bash

# install necessary softwares
sudo apt update -y
sudo apt install -y zsh curl tmux python3-pip fontconfig  silversearcher-ag 

# these packages are not available on Ubuntu <= 18.04
sudo apt install -y fzf universal-ctags ripgrep

# Check if oh-my-zsh is installed
OMZDIR="$HOME/.oh-my-zsh"
if [[ ! -d "$OMZDIR" ]]; then
  echo 'Installing oh-my-zsh'
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo 'Updating oh-my-zsh'
fi

